# Generated by Django 4.2.10 on 2024-08-28 06:45

from django.db import migrations, models
import foodapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=foodapp.models.generate_unique_code_order, max_length=20, primary_key=True, serialize=False),
        ),
    ]
