# Generated by Django 4.2.10 on 2024-08-14 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_catagory_delivery_staff_menu_order_user_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='catagaroy_id',
            new_name='catagory_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_ammount',
        ),
        migrations.RemoveField(
            model_name='order_items',
            name='order_item_id',
        ),
    ]
