# Generated by Django 4.2.10 on 2024-08-29 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_alter_order_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_items',
            name='quantity',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
