# Generated by Django 4.2.10 on 2024-09-23 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_alter_order_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_varified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('R0', 'Pending'), ('R1', 'On Delivery'), ('R2', 'Delivered')], default='R0', max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('R0', 'Pending'), ('R1', 'On Delivery'), ('R2', 'Delivered')], default='R0', max_length=2),
        ),
    ]
