# Generated by Django 4.2.10 on 2024-08-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_alter_order_user_id_alter_review_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_id',
            field=models.CharField(default='', max_length=8, unique=True),
        ),
    ]
