# Generated by Django 4.2.10 on 2024-08-16 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_menu_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='food-deivery/user_images/menu-images'),
        ),
    ]
