# Generated by Django 4.2.10 on 2024-08-16 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0006_menu_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='http://127.0.0.1:8000/menu/food-deivery/user_images/menu-images'),
        ),
    ]
