# Generated by Django 4.2.16 on 2024-10-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_profile_user_type_alter_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'admin'), (2, 'cashier'), (3, 'delivery man'), (4, 'customer')], default=4, editable=False),
        ),
    ]
